spring:
  datasource:
    uri: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandartImpl