spring:
  datasource:
    uri: jdbc:mysql://localhost:3306/rentdb?createDatabaseIfNotExist=true
    username: kolian0071
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandartImpl